spring:
    jpa:
        hibernate:
            ddl-auto:update
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/banco
        username: root
        password: 2023
        driverClassName: com.mysql.cj.jdbc.Driver
    show-sql: true
    properties:
        hibernate:
           format_sql:true
